FROM python:3.11.5-alpine

WORKDIR /app

COPY ./requirements.txt /app

RUN pip install --no-cache-dir -r requirements.txt

# Add Tini, that will take care of handling the main process
RUN apk add --no-cache tini

ENTRYPOINT ["/sbin/tini", "--"]

COPY . .

CMD ["gunicorn",  "-b", "0.0.0.0:8000", "run:app", "-c", "gunicorn_config.py"]
